### ISSUE TITLE
Proxy Handler could not detect JSON

### ISSUE THREAD

**Issue by masudrashid** [alhazmy13/serverless-offline-python#21]
This issue was [fixed](https://github.com/dherault/serverless-offline/pull/716) in dherault/serverless-offline. Please integrate this simple single-word-edit fix here. Thanks in advance.

**Comment by alhazmy13** [comment]
Dear @masudrashid ,

Fixed with version 3.22.3

Thanks

**Comment by masudrashid** [comment]
Didn't expect such quick response. Thanks a lot
